config/routes.rb
Rails.application.routes.draw do
 mount Ckeditor::Engine => '/ckeditor'
 
  resources :categories, only: [:show]
  resources :pages, only: [:show]
 
  namespace :admin do
    resources :types, except: [:show]
    resources :menus, except: [:show]
    resources :pages # /admin/pages
    resources :categories
 end

   Page.where.not(slug: nil).all.each do |page|
     get "/#{page.slug}", controller: "pages", action: "show", id: page.id
   end

  root 'admin/pages#index'
 
end

app/controllers/admin/types_controller.rb
module Admin
  class TypesController < ApplicationController
    def index
      @types = Type.all
    end

    def new
      @type = Type.new
      3.times { @type.field_definitions.build } 
    end

    def edit
      @type = Type.find params[:id]
      3.times { @type.field_definitions.build } 
    end

    def create
      @type = Type.new type_params
      if @type.save
       redirect_to admin_types_path, notice: "Type created."
      else
       render :new, alert: "Type wasn't created."
      end
    end

    def update
      @type = Type.find params[:id]
      if @type.update_attributes type_params
        redirect_to admin_types_path, notice: "Type updated."
      else
        render :edit, alert: "Type wasn't updated."
      end
    end

    def destroy
      @type = type.find params[:id]
      if @type.destroy
        redirect_to admin_types_path, notice: "Type deleted."
      else
        redirect_to admin_types_path, alert: "type was not deleted."
      end
    end

    protected
    
    def type_params
      params.require(:type).permit(:name, :field_definitions_attributes => [:key, :id])
    end
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/admin/types/_form.html.haml
=form_for ["admin", @type] do |f|
  %p
  =f.text_field :name, placeholder: "Name", class: "form-control input-lg"

  %h3 Custom fields
  
  =f.fields_for :field_definitions do |c|
    %p
      =c.text_field :key, class: "form-control"
      =c.hidden_field :id

  %p
    =f.submit 

app/views/admin/types/edit.html.haml
%h1 Edit Type

=render "form"

app/views/admin/types/index.html.haml
%h1 Types

%ul
  -@types.each do |type|
    %li
      =type.name
      =link_to "edit", edit_admin_type_path(type)
      %ul
        -type.field_definitions.each do |field|
          %li=field.key

%p
  =link_to "New Type", new_admin_type_path

app/views/admin/types/new.html.haml
%h1 New Type

=render "form"