config/routes.rb
Rails.application.routes.draw do
 mount Ckeditor::Engine => '/ckeditor'
 
  resources :categories, only: [:show]
  resources :pages, only: [:show]
 
  namespace :admin do
    resources :types, except: [:show]
    resources :menus, except: [:show]
    resources :pages # /admin/pages
    resources :categories
 end

   Page.where.not(slug: nil).all.each do |page|
     get "/#{page.slug}", controller: "pages", action: "show", id: page.id
   end

  root 'admin/pages#index'
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def url_for_page page
		root_path + if page.slug.present?
			page.slug
		else
			"pages/#{page.id}"
		end
	end

	def url_for_menu_item menu_item
		if menu_item.url.match /:\/\// #http://, ftp://, etc
			menu_item.url
		else
			root_path + menu_item.url
		end

	end

end

app/views/application/_admin_nav.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#main-nav", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to "Tuts+ CMS", root_path, class: "navbar-brand"
    / Collect the nav links, forms, and other content for toggling
    #main-nav.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          =link_to "Content", admin_pages_path
        %li 
          =link_to "Categories", admin_categories_path  
        %li 
          =link_to "Menus", admin_menus_path 
        %li 
          =link_to "Types", admin_types_path  